grails-app/domain/demo/Extra.groovy
package demo

import grails.compiler.GrailsCompileStatic
import groovy.transform.EqualsAndHashCode
import groovy.transform.ToString

@ToString
@EqualsAndHashCode
@GrailsCompileStatic
class Extra {
    String name

    static constraints = {
        name nullable: false, blank: false
    }
}

grails-app/controllers/demo/ExtraController.groovy
package demo

import grails.validation.ValidationException
import groovy.transform.CompileStatic
import org.springframework.context.MessageSource

@SuppressWarnings(['FactoryMethodName', 'ReturnNullFromCatchBlock'])
@CompileStatic
class ExtraController implements BeanMessage {

    ExtraDataService extraDataService
    MessageSource messageSource

    static allowedMethods = [
            index: 'GET',
            show: 'GET',
            create: 'GET',
            save: 'POST',
            edit: 'GET',
            update: 'PUT',
            delete: 'DELETE',
    ]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond extraDataService.list(params), model: [extraCount: extraDataService.count()]
    }

    def show(Long id) {
        respond extraDataService.get(id)
    }

    def create() {
        respond new Extra(params)
    }

    def save(NameCommand cmd) {
        if ( cmd.hasErrors() ) {
            respond cmd.errors, view: 'edit'
            return
        }

        Extra extra
        try {
            extra = extraDataService.save(cmd.name)
        } catch (ValidationException e) {
            flash.error = beanMessage(e, messageSource).join(',')
            render view: 'create'
            return
        }

        flash.message = messageSource.getMessage('default.created.message', [extraMessage(), extra.id] as Object[], 'Extra created', request.locale)
        redirect action: 'show', id: extra.id
    }

    def edit(Long id) {
        respond extraDataService.get(id)
    }

    def update(NameIdCommand cmd) {
        if ( cmd.hasErrors() ) {
            respond cmd.errors, view: 'edit'
            return
        }

        Extra extra
        try {
            extra = extraDataService.update(cmd.id, cmd.name)
        } catch (ValidationException e) {
            flash.error = beanMessage(e, messageSource).join(',')
            render view: 'edit'
            return
        }
        flash.message = messageSource.getMessage('default.updated.message', [extraMessage(), extra.id] as Object[], 'Extra updated', request.locale)
        redirect action: 'show', id: extra.id
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        extraDataService.delete(id)
        flash.message = messageSource.getMessage('default.deleted.message', [extraMessage(), id] as Object[], 'Extra deleted', request.locale)
        redirect action: 'index', method: 'GET'
    }

    protected void notFound() {
        flash.message = messageSource.getMessage('default.not.found.message', [extraMessage(), params.id] as Object[], 'Extra not found', request.locale)
        redirect action: 'index', method: 'GET'
    }

    protected String extraMessage() {
        messageSource.getMessage('extra.label', [] as Object[], 'Extra', request.locale)
    }
}

grails-app/views/extra/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'extra.label', default: 'Extra')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-extra" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <g:render template="/templates/nav"/>
        <div id="create-extra" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.extra}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.extra}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.extra}" method="POST">
                <fieldset class="form">
                    <f:all bean="extra"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/extra/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'extra.label', default: 'Extra')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-extra" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <g:render template="/templates/nav"/>
        <div id="edit-extra" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.extra}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.extra}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.extra}" method="PUT">
                <g:hiddenField name="version" value="${this.extra?.version}" />
                <fieldset class="form">
                    <f:all bean="extra"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/extra/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'extra.label', default: 'Extra')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-extra" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <g:render template="/templates/nav"/>
        <div id="list-extra" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${extraList}" />

            <div class="pagination">
                <g:paginate total="${extraCount ?: 0}" />
            </div>
        </div>
        <fieldset class="buttons">
            <ul>
                <li><g:link controller="extra" class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </fieldset>
    </body>
</html>

grails-app/views/extra/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'extra.label', default: 'Extra')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-extra" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <g:render template="/templates/nav"/>
        <div id="show-extra" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="extra" />
            <g:form resource="${this.extra}" method="DELETE">
                <fieldset class="buttons">
                    <g:link controller="extra" class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link>
                    <g:link class="edit" action="edit" resource="${this.extra}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>