grails-app/domain/demo/Room.groovy
package demo

import grails.compiler.GrailsCompileStatic
import groovy.transform.EqualsAndHashCode
import groovy.transform.ToString

@ToString
@EqualsAndHashCode
@GrailsCompileStatic
class Room {
    String name

    static constraints = {
        name nullable: false, blank: false
    }
}

grails-app/controllers/demo/RoomController.groovy
package demo


import com.aop.annotations.FailOrSuccessOperationRegister
import com.aop.aspects.HandledExceptionAop
import com.aop.metrics.MetricTypes
import grails.validation.ValidationException
import groovy.transform.CompileStatic
import jdk.internal.platform.Metrics
import org.springframework.context.MessageSource

@SuppressWarnings(['FactoryMethodName', 'ReturnNullFromCatchBlock'])
@CompileStatic
class RoomController implements BeanMessage {

    RoomDataService roomDataService

    MessageSource messageSource

    static allowedMethods = [
            index: 'GET',
            show: 'GET',
            save: 'POST',
            edit: 'GET',
            update: 'PUT',
            delete: 'DELETE',
    ]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        System.out.println("BBB")
        testFun()
        respond roomDataService.list(params), model: [roomCount: roomDataService.count()]
    }

    @FailOrSuccessOperationRegister(metricName = MetricTypes.OblikRestAccess)
    def testFun(){
        try {
            Integer intV = Random.newInstance().nextInt(10)
            System.out.println("Rand: ${intV}")
            if (intV > 2) throw new ArithmeticException()
            System.out.println("OK")
        } catch (Exception e) {
            System.out.println("REST EXCEPTION: ${e.getClass().getCanonicalName()} , ${e.getMessage()}")
        }
        System.out.println("testFun")
    }

    def show(Long id) {
        respond roomDataService.get(id)
    }

    def create() {
        respond new Room(params)
    }

    def save(Room room) {
        if (room == null) {
            notFound()
            return
        }

        try {
            roomDataService.save(room)
        } catch (ValidationException e) {
            flash.error = beanMessage(e, messageSource).join(',')
            render view: 'create'
            return
        }

        flash.message = messageSource.getMessage('default.created.message', [roomMessage(), room.id] as Object[], 'Room created', request.locale)
        redirect room
    }

    def edit(Long id) {
        respond roomDataService.get(id)
    }

    def update(Room room) {
        if (room == null) {
            notFound()
            return
        }

        try {
            roomDataService.save(room)
        } catch (ValidationException e) {
            flash.error = beanMessage(e, messageSource).join(',')
            render view: 'edit'
            return
        }

        flash.message = messageSource.getMessage('default.updated.message', [roomMessage(), room.id] as Object[], 'Room updated', request.locale)
        redirect room
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        roomDataService.delete(id)

        flash.message = messageSource.getMessage('default.deleted.message', [roomMessage(), id] as Object[], 'Room deleted', request.locale)
        redirect action: 'index', method: 'GET'
    }

    protected void notFound() {
        flash.message = messageSource.getMessage('default.not.found.message', [roomMessage(), params.id] as Object[], 'Room not found', request.locale)
        redirect action: 'index', method: 'GET'
    }

    protected String roomMessage() {
        messageSource.getMessage('room.label', [] as Object[], 'Room', request.locale)
    }
}

grails-app/views/room/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'room.label', default: 'Room')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-room" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <g:render template="/templates/nav"/>
        <div id="create-room" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.room}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.room}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.room}" method="POST">
                <fieldset class="form">
                    <f:all bean="room"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/room/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'room.label', default: 'Room')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-room" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <g:render template="/templates/nav"/>
        <div id="edit-room" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.room}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.room}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.room}" method="PUT">
                <g:hiddenField name="version" value="${this.room?.version}" />
                <fieldset class="form">
                    <f:all bean="room"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/room/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'room.label', default: 'Room')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-room" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <g:render template="/templates/nav"/>
        <div id="list-room" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${roomList}" />

            <div class="pagination">
                <g:paginate total="${roomCount ?: 0}" />
            </div>
        </div>
        <fieldset class="buttons">
            <ul>
                <li><g:link controller="room" class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </fieldset>
    </body>
</html>

grails-app/views/room/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'room.label', default: 'Room')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-room" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <g:render template="/templates/nav"/>
        <div id="show-room" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="room" />
            <g:form resource="${this.room}" method="DELETE">
                <fieldset class="buttons">
                    <g:link controller="room" class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link>
                    <g:link class="edit" action="edit" resource="${this.room}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>