grails-app/domain/demo/Booking.groovy
package demo

import grails.compiler.GrailsCompileStatic
import groovy.transform.EqualsAndHashCode
import groovy.transform.ToString

@ToString
@EqualsAndHashCode
@GrailsCompileStatic
class Booking {
    String name
    String email
    String telephone
    Date arrival
    Date departure
    int adults = 1
    int children = 0
    int babys = 0

    static constraints = {
        name nullable: false, blank: false
        email nullable: false, blank: false, email: true
        telephone nullable: true
        arrival nullable: false
        departure nullable: false
        adults min: 1
        children min: 0
        babys min: 0
    }
}

grails-app/domain/demo/BookingExtra.groovy
package demo

import grails.compiler.GrailsCompileStatic
import groovy.transform.EqualsAndHashCode
import groovy.transform.ToString

@ToString
@EqualsAndHashCode
@GrailsCompileStatic
class BookingExtra {
    Booking booking
    Extra extra

    static mapping = {
        booking nullable: false
        extra nullable: false
    }
}

grails-app/domain/demo/BookingRoom.groovy
package demo

import grails.compiler.GrailsCompileStatic
import groovy.transform.EqualsAndHashCode
import groovy.transform.ToString

@ToString
@EqualsAndHashCode
@GrailsCompileStatic
class BookingRoom {
    Booking booking
    Room room

    static mapping = {
        booking nullable: false
        room nullable: false
    }
}

grails-app/domain/demo/Extra.groovy
package demo

import grails.compiler.GrailsCompileStatic
import groovy.transform.EqualsAndHashCode
import groovy.transform.ToString

@ToString
@EqualsAndHashCode
@GrailsCompileStatic
class Extra {
    String name

    static constraints = {
        name nullable: false, blank: false
    }
}

grails-app/domain/demo/Room.groovy
package demo

import grails.compiler.GrailsCompileStatic
import groovy.transform.EqualsAndHashCode
import groovy.transform.ToString

@ToString
@EqualsAndHashCode
@GrailsCompileStatic
class Room {
    String name

    static constraints = {
        name nullable: false, blank: false
    }
}

grails-app/controllers/demo/BookingController.groovy
package demo

import grails.validation.ValidationException
import groovy.transform.CompileStatic
import org.springframework.context.MessageSource

@SuppressWarnings(['FactoryMethodName', 'ReturnNullFromCatchBlock'])
@CompileStatic
class BookingController implements BeanMessage {

    def TestService testService
    BookingDataService bookingDataService
    BookingExtraDataService bookingExtraDataService
    BookingRoomDataService bookingRoomDataService
    RoomDataService roomDataService
    ExtraDataService extraDataService
    MessageSource messageSource
    BookingService bookingService

    static allowedMethods = [
            index: 'GET',
            create: 'GET',
            save: 'POST',
            edit: 'GET',
            update: 'PUT',
            delete: 'DELETE',
    ]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        testService.serviceMethod()
        respond bookingDataService.list(params), model: [bookingCount: bookingDataService.count()]
    }

    def show(Long id) {
        Booking booking = bookingDataService.get(id)
        if ( !booking ) {
            notFound()
            return
        }
        List<Extra> extraList = bookingExtraDataService.findBookingExtraExtra(booking)
        List<Room> roomList = bookingRoomDataService.findBookingRoomRoom(booking)
        [booking: booking, roomList: roomList, extraList: extraList]
    }

    def create() {
        List<Room> roomList = roomDataService.list([:])
        List<Extra> extraList = extraDataService.list([:])
        [
                booking: new Booking(params),
                roomList: roomList,
                extraList: extraList,
        ]
    }

    def save(SaveBookingCommand cmd) {
        if ( cmd.hasErrors() ) {
            respond cmd.errors, view: 'edit'
            return
        }

        Booking booking
        try {
            booking = bookingService.save(cmd as Booking, cmd.rooms, cmd.extras)
        } catch (ValidationException e) {
            flash.error = beanMessage(e, messageSource).join(',')
            render view: 'create'
            return
        }

        flash.message = messageSource.getMessage('default.created.message', [bookingMessage(), booking.id] as Object[], 'Booking created', request.locale)
        redirect action: 'show', id: booking.id
    }

    def edit(Long id) {
        Booking booking = bookingDataService.get(id)
        if ( !booking ) {
            notFound()
            return
        }
        List<Room> roomList = roomDataService.list([:])
        List<Extra> extraList = extraDataService.list([:])

        List<Extra> bookingExtraList = bookingExtraDataService.findBookingExtraExtra(booking)
        List<Room> bookingRoomList = bookingRoomDataService.findBookingRoomRoom(booking)
        [
                booking: booking,
                roomList: roomList,
                extraList: extraList,
                bookingExtraList: bookingExtraList,
                bookingRoomList: bookingRoomList,
        ]
    }

    def update(EditBookingCommand cmd) {
        if ( cmd.hasErrors() ) {
            respond cmd.errors, view: 'edit'
            return
        }

        Booking booking
        try {
            booking = bookingService.update(cmd as Booking, cmd.rooms, cmd.extras)
        } catch (ValidationException e) {
            flash.error = beanMessage(e, messageSource).join(',')
            render view: 'edit'
            return
        }

        flash.message = messageSource.getMessage('default.updated.message', [bookingMessage(), booking.id] as Object[], 'Booking update', request.locale)
        redirect action: 'show', id: booking.id
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        bookingService.delete(id)
        flash.message = messageSource.getMessage('default.deleted.message', [bookingMessage(), id] as Object[], 'Booking deleted', request.locale)
        redirect action: 'index', method: 'GET'
    }

    protected void notFound() {
        flash.message = messageSource.getMessage('default.not.found.message', [bookingMessage(), params.id] as Object[], 'Booking not found', request.locale)
        redirect action: 'index', method: 'GET'
    }

    protected String bookingMessage() {
        messageSource.getMessage('booking.label', [] as Object[], 'Booking', request.locale)
    }
}

grails-app/views/booking/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'booking.label', default: 'Booking')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-booking" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <g:render template="/templates/nav"/>
        <div id="create-booking" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.booking}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.booking}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.booking}" method="POST">
                <fieldset class="form">
                    <f:all bean="booking"/>

                    <g:if test="${roomList}">
                        <div class="fieldcontain">
                            <label for="rooms"><g:message code="booking.rooms.label" default="Rooms" /></label>
                            <ol class="property-list">
                                <g:each var="room" in="${roomList}">
                                    <li class="fieldcontain">
                                        <span class="property-label">${room.name}</span>
                                        <span>&nbsp;</span>
                                        <g:checkBox name="rooms" value="${room.id}" checked="false" />
                                    </li>
                                </g:each>
                            </ol>
                        </div>
                    </g:if>

                    <g:if test="${extraList}">
                        <div class="fieldcontain">
                            <label for="extras"><g:message code="booking.extras.label" default="Extras" /></label>
                            <ol class="property-list">
                                <g:each var="extra" in="${extraList}">
                                    <li class="fieldcontain">
                                        <span class="property-label">${extra.name}</span>
                                        <span>&nbsp;</span>
                                        <g:checkBox name="extras" value="${extra.id}" checked="false" />
                                    </li>
                                </g:each>
                            </ol>
                        </div>
                    </g:if>

                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/booking/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'booking.label', default: 'Booking')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-booking" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <g:render template="/templates/nav"/>
        <div id="edit-booking" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.booking}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.booking}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.booking}" method="PUT">
                <g:hiddenField name="version" value="${this.booking?.version}" />
                <fieldset class="form">
                    <f:all bean="booking"/>

                    <g:if test="${roomList}">
                        <div class="fieldcontain">
                            <label for="rooms"><g:message code="booking.rooms.label" default="Rooms" /></label>
                            <ol class="property-list">
                                <g:each var="room" in="${roomList}">
                                    <li class="fieldcontain">
                                        <span class="property-label">${room.name}</span>
                                        <span>&nbsp;</span>
                                        <g:checkBox name="rooms" value="${room.id}" checked="${bookingRoomList.any { it.id == room.id }}" />
                                    </li>
                                </g:each>
                            </ol>
                        </div>
                    </g:if>

                    <g:if test="${extraList}">
                        <div class="fieldcontain">
                            <label for="extras"><g:message code="booking.extras.label" default="Extras" /></label>
                            <ol class="property-list">
                                <g:each var="extra" in="${extraList}">
                                    <li class="fieldcontain">
                                        <span class="property-label">${extra.name}</span>
                                        <span>&nbsp;</span>
                                        <g:checkBox name="extras" value="${extra.id}" checked="${bookingExtraList.any { it.id == extra.id }}" />
                                    </li>
                                </g:each>
                            </ol>
                        </div>
                    </g:if>


                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/booking/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'booking.label', default: 'Booking')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-booking" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <g:render template="/templates/nav"/>
        <div id="list-booking" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${bookingList}" />

            <div class="pagination">
                <g:paginate total="${bookingCount ?: 0}" />
            </div>
        </div>
        <fieldset class="buttons">
            <ul>
                <li><g:link controller="booking" class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </fieldset>
    </body>
</html>

grails-app/views/booking/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'booking.label', default: 'Booking')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-booking" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <g:render template="/templates/nav"/>
        <div id="show-booking" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="booking" />
            <ol class="property-list booking">
                <g:if test="${roomList}">
                    <li class="fieldcontain">
                        <span id="rooms-label" class="property-label"><g:message code="booking.rooms.label" default="Rooms"/></span>
                        <div class="property-value" aria-labelledby="name-label">${roomList*.name.join(',')}</div>
                    </li>
                </g:if>
                <g:if test="${extraList}">
                    <li class="fieldcontain">
                        <span id="extras-label" class="property-label"><g:message code="booking.extras.label" default="Extras"/></span>
                        <div class="property-value" aria-labelledby="name-label">${extraList*.name.join(',')}</div>
                    </li>
                </g:if>
            </ol>
            <g:form resource="${this.booking}" method="DELETE">
                <fieldset class="buttons">
                    <g:link controller="booking" class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link>
                    <g:link class="edit" action="edit" resource="${this.booking}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>